import { ROUTES } from "@/constants/routes";
import { ADMIN_ROUTES } from "../admin.constants";
import { bannerIdParams, bannerImagesQueryParams, bannerReorderSchema, bannerUpsertRequestSchema, imageIdParams } from "./banner.schema";
import { badRequestError, errorResponse, forbiddenError, notFoundError, unauthorizedError } from "@/docs/swagger/helpers/error.helper";
import { successResponse } from "@/docs/swagger/helpers/success.helper";

const BANNER_BASE = `${ROUTES.ADMIN}${ADMIN_ROUTES.BANNER}`;

export const adminBannerSwagger = {
  tags: [
    {
      name: "Admin Banners",
      description: "Admin banner management"
    }
  ],

  paths: {
    [`${BANNER_BASE}`]: {
      get: {
        tags: ["Admin Banners"],
        summary: "Get all banners",
        description: `
Retrieve a list of banners.

Each banner includes a resolved \`url\` field for preview purposes.

Note:
- The \`url\` field is generated by the server.
- It represents a resolved path (e.g. collection or category route).
- The format may vary depending on frontend routing implementation.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    success: {
                      type: "boolean",
                      example: true
                    },
                    data: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          id: { type: "number", example: 13 },
                          title: { type: "string", example: "new arrivals collections" },
                          placement: {
                            type: "string",
                            example: "homepage_hero"
                          },
                          imageKey: {
                            type: "string",
                            example: "banners/123.webp"
                          },
                          targetType: {
                            type: "string",
                            example: "collection"
                          },
                          url: {
                            type: "string",
                            example: "/collections/new-arrivals",
                            description: "Resolved URL path for the banner target (for preview/navigation)"
                          },
                          status: {
                            type: "string",
                            example: "ACTIVE"
                          },
                          sortOrder: {
                            type: "number",
                            example: 10
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },

          401: unauthorizedError(),
          403: forbiddenError("Admin access required")
        }
      },

      post: {
        tags: ["Admin Banners"],
        summary: "Create banner",
        description: `
Create a new banner.

This endpoint accepts **multipart/form-data** with image upload and metadata fields.

Refer to the request body for field details and examples.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        requestBody: {
          required: true,
          content: {
            "multipart/form-data": {
              schema: bannerUpsertRequestSchema
            }
          }
        },

        responses: {
          201: {
            description: "Created",
            content: {
              "application/json": {
                schema: successResponse({
                  message: "Banner created"
                })
              }
            }
          },

          400: badRequestError("Invalid request payload"),
          401: unauthorizedError(),
          403: forbiddenError("Admin access required")
        }
      }
    },

    [`${BANNER_BASE}/{bannerId}`]: {
      get: {
        tags: ["Admin Banners"],
        summary: "Get banner by ID",
        description: `
Retrieve a banner by its ID.

Returns banner details including title, placement, target, and image reference.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        requestParams: {
          path: bannerIdParams
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    success: {
                      type: "boolean",
                      example: true
                    },
                    data: {
                      type: "object",
                      properties: {
                        id: { type: "number", example: 12 },
                        title: { type: "string", example: "new arrivals collection" },
                        placement: {
                          type: "string",
                          example: "homepage_hero"
                        },
                        image: {
                          type: "object",
                          properties: {
                            id: { type: "string", example: "158" },
                            imageKey: {
                              type: "string",
                              example: "banners/123.webp"
                            }
                          }
                        },
                        targetType: {
                          type: "string",
                          example: "collection"
                        },
                        targetId: {
                          type: "string",
                          example: "6"
                        },
                        status: {
                          type: "string",
                          example: "ACTIVE"
                        }
                      }
                    }
                  }
                }
              }
            }
          },

          401: unauthorizedError(),
          403: forbiddenError("Admin access required"),
          404: notFoundError("Banner not found")
        }
      },

      put: {
        tags: ["Admin Banners"],
        summary: "Update banner",
        description: `
Update an existing banner.

This endpoint accepts **multipart/form-data** with image upload and metadata fields.

All fields follow the same structure as create banner.
Existing data will be updated based on the provided input.

If no new image file is provided, the existing image will be retained.

Refer to the request body for field details and examples.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        requestParams: {
          path: bannerIdParams
        },

        requestBody: {
          required: true,
          content: {
            "multipart/form-data": {
              schema: bannerUpsertRequestSchema
            }
          }
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: successResponse({
                  message: "Banner updated"
                })
              }
            }
          },

          400: badRequestError("Invalid request payload"),
          401: unauthorizedError(),
          403: forbiddenError("Admin access required"),
          404: notFoundError("Banner not found")
        }
      },

      delete: {
        tags: ["Admin Banners"],
        summary: "Delete banner",
        description: `
Delete a banner by its ID.

Note:
- This operation only removes the banner record.
- The associated image will not be deleted automatically.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        requestParams: {
          path: bannerIdParams
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: successResponse({
                  message: "Banner removed"
                })
              }
            }
          },

          401: unauthorizedError(),
          403: forbiddenError("Admin access required"),
          404: notFoundError("Banner not found")
        }
      }
    },

    [`${BANNER_BASE}/actions/reorder`]: {
      put: {
        tags: ["Admin Banners"],
        summary: "Reorder banners",
        description: `
Reorder banners.

This endpoint is typically used for drag-and-drop sorting in the admin UI.

Only the \`sortOrder\` field will be updated.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: bannerReorderSchema
            }
          }
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: successResponse({
                  message: "Banner reordered"
                })
              }
            }
          },

          400: badRequestError("Invalid request payload"),
          401: unauthorizedError(),
          403: forbiddenError("Admin access required")
        }
      }
    },

    [`${BANNER_BASE}/meta`]: {
      get: {
        tags: ["Admin Banners"],
        summary: "Get banner meta options",
        description: `
Retrieve available banner options for form usage.

Used to populate select (dropdown) inputs such as placements and target types.

All values are predefined by the server and not sourced from database records.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    success: {
                      type: "boolean",
                      example: true
                    },
                    data: {
                      type: "object",
                      properties: {
                        placements: {
                          type: "array",
                          items: {
                            type: "object",
                            properties: {
                              value: {
                                type: "string",
                                example: "homepage_hero"
                              },
                              label: {
                                type: "string",
                                example: "Homepage Hero"
                              }
                            }
                          }
                        },
                        targetTypes: {
                          type: "array",
                          items: {
                            type: "object",
                            properties: {
                              value: {
                                type: "string",
                                example: "collection"
                              },
                              label: {
                                type: "string",
                                example: "Collection"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },

          401: unauthorizedError(),
          403: forbiddenError("Admin access required")
        }
      }
    },

    [`${BANNER_BASE}/images`]: {
      get: {
        tags: ["Admin Banners"],
        summary: "Get banner images",
        description: `
Retrieve a paginated list of banner images.

This endpoint acts as an image library, allowing existing images to be reused when creating or updating banners.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        requestParams: {
          query: bannerImagesQueryParams
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    success: {
                      type: "boolean",
                      example: true
                    },
                    data: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          id: { type: "number", example: 158 },
                          imageKey: {
                            type: "string",
                            example: "banners/123.webp"
                          },
                          width: { type: "number", example: 1200 },
                          height: { type: "number", example: 400 }
                        }
                      }
                    },
                    meta: {
                      type: "object",
                      properties: {
                        page: { type: "number", example: 1 },
                        limit: { type: "number", example: 10 },
                        total: { type: "number", example: 2 },
                        totalPages: { type: "number", example: 1 },
                        hasNext: { type: "boolean", example: false },
                        hasPrev: { type: "boolean", example: false }
                      }
                    }
                  }
                }
              }
            }
          },

          401: unauthorizedError(),
          403: forbiddenError("Admin access required")
        }
      }
    },

    [`${BANNER_BASE}/images/{imageId}`]: {
      delete: {
        tags: ["Admin Banners"],
        summary: "Delete banner image",
        description: `
Delete a banner image by its ID.

Note:
- The image cannot be deleted if it is still used by any banner.
- Make sure the image is not referenced before attempting to remove it.
`,

        security: [
          {
            cookieAuth: []
          }
        ],

        requestParams: {
          path: imageIdParams
        },

        responses: {
          200: {
            description: "OK",
            content: {
              "application/json": {
                schema: successResponse({
                  message: "Banner image removed"
                })
              }
            }
          },

          400: errorResponse({
            code: "INVALID_REFERENCE",
            message: "Invalid foreign key reference",
            description: "Image cannot be deleted because it is still used by one or more banners"
          }),

          401: unauthorizedError(),
          403: forbiddenError("Admin access required"),
          404: notFoundError("Banner image not found")
        }
      }
    }
  }
};
